### ISSUE TITLE
Flat obstacles in 3D space

### ISSUE THREAD

**Issue by crackalamoo** [tum-pbs/PhiFlow#157]
Hi,

I was wondering what is the best way to represent a flat (or nearly flat) obstacle in 3D space. (Like a sheet of paper.) I tried `OBSTACLE = Obstacle(Box(x=(5, 95), y=(50, 51), z=(0,100))` and this seemed to possibly work, but I couldn't tell for sure. When I added a rotation with `OBSTACLE = Obstacle(Box(x=(5, 95), y=(50, 51), z=(0,100)).rotated((0,0,0.15)))` it's even harder for me to tell if it's working or not.

I am using the default solver (MacCormack) which I believe is grid-based. I wonder if a particle-based solver you have would better deal with this type of boundary condition, and if not, if there's another way to ensure that no fluid gets past this thin obstacle. Or perhaps the simulation is working as it is?

I would also like to have flat triangular obstacles, but I haven't found a way to do this yet. What is the best way to accomplish this?

Any guidance here would be much appreciated. Thank you!

Here is the animation of a rotated obstacle (XY-plane cross-section of the 3D simulation):
![rot](https://github.com/tum-pbs/PhiFlow/assets/37599247/537949d3-4740-4a37-8ee8-64132fb51f0f)
Here is the non-rotated obstacle:
![no_rot](https://github.com/tum-pbs/PhiFlow/assets/37599247/95a9fcec-4c33-4e16-b22c-ba96a0cf87a3)

**Comment by holl-** [comment]
Hi @crackalamoo,

The obstacle is mapped to the grid in order to work with the simulation. It needs to be thick enough to include the centers of all connected grid cells, else there will be holes. In order to see whether resampling works correctly, you can plot the resampled obstacle like so:

```python
box = Box(x=(5, 95), y=(50, 51))
rotated = box.rotated(0.15)
show(CenteredGrid(box, x=64, y=64, bounds=Box(x=100, y=100)),
     CenteredGrid(rotated, x=64, y=64, bounds=Box(x=100, y=100)))
```

![obstacles](https://github.com/tum-pbs/PhiFlow/assets/6258959/d738b0f6-2fbd-4470-a55d-ccea3215a3a9)

Or for 3D, you can plot slices, e.g.

```python
box = Box(x=(5, 95), y=(50, 51), z=(0,100))
rotated = box.rotated(vec(x=0,y=0,z=0.15))
show(resample(box, smoke).z[15], resample(rotated, smoke).z[31])
```

![obstacle_slice](https://github.com/tum-pbs/PhiFlow/assets/6258959/e06a6aa2-ef7a-4b5c-be45-d19bb65eb34c)

Here, the obstacle was too thin to be sampled correctly on the grid.

However, with a thick enough obstacle, the simulation should work. Here is a 2D example:

![2D_flat](https://github.com/tum-pbs/PhiFlow/assets/6258959/0b54dea2-a496-478d-9f5e-d36bacfa64f0)

**Comment by holl-** [comment]
Also if there are strange numerical artefacts, you might want disable the pressure solve preconditioner (if you are using one).

**Comment by crackalamoo** [comment]
Hi @holl- 

Thank you for your prompt response, this is very helpful. Is there a way to create flat triangular obstacles in 3D space? Can this be accomplished with heightmaps as in #147 ?

**Comment by holl-** [comment]
Do you mean a thin triangle or a prism with a triangular cross section? Do you have a picture of what the geometry should look like?

**Comment by crackalamoo** [comment]
I mean a thin triangle. Here is a plot in Matplotlib:

![triangle](https://github.com/tum-pbs/PhiFlow/assets/37599247/8e1439c7-b48f-4d30-a65b-02513f9408a3)

**Comment by holl-** [comment]
Okay, for this you could approximate your triangle with multiple boxes, i.e. something like this

```python
y = math.linspace(0, 2, instance(tri_boxes=30))
g = geom.rotate(Box(x=.5 * (y[:-1] + y[1:]), y=(y[:-1], y[1:])), .2, pivot=vec(x=0, y=0))
show(CenteredGrid(g, x=64, y=64, bounds=g.bounding_box()))
```

It's not perfect but should do the trick. In this example, I build up a triangle from 30 boxes. The union of boxes is represented by a Box with an instance dimension listing the individual properties.

**Comment by crackalamoo** [comment]
Thank you, this answers my question! I'll close this issue.
